name: Update WakaTime Stats

on:
  schedule:
    - cron: '45 21 * * *'  # Runs daily at 23:55 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download WakaTime Stats SVG
        run: |
          curl -s "https://wakatime-readme-stats.vercel.app/api/wakatimeStats?username=LauraAllObe&components=3&title_prefix=Laura%27s&bg_color=fffbea&title_color=6b4e16&text_color=4b3b0c&logo_color=a68b2c&border_color=e0d3a8&border_width=2&border_radius=10&component1=type%3Dweekly_avg%26chart_type%3Dradar%26start_day%3Dmo%26y_axis%3Dtrue%26y_axis_label%3Dtrue%26hide_legend%3Dtrue%26hide_total%3Dtrue&component2=type%3Dbasic&component3=type%3Dheatmap%26start_day%3Dmo" -o stats.svg

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add stats.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update stats.svg"
          git push
